/* Export your custom icon components here. */
export { default as BrandIcon } from './brand-icon';
export { default as Give } from './give';
export { default as Groups } from './groups';
export { default as FindGroup } from './findgroup';
export { default as Cal } from './cal';
export { default as Hands } from './hands';
export { default as HandShake } from './handshake';
export { default as QrCode } from './qr-code';
